# Generated by Django 4.2.11 on 2024-03-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactprofile',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
